//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  litter: Litter;
  litterConnection: LitterConnection;
  upcomingLitter: UpcomingLitter;
  upcomingLitterConnection: UpcomingLitterConnection;
  page: Page;
  pageConnection: PageConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
  reviews: Reviews;
  reviewsConnection: ReviewsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLitterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLitterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LitterFilter>;
};


export type QueryUpcomingLitterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUpcomingLitterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UpcomingLitterFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryReviewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
};

export type DocumentFilter = {
  litter?: InputMaybe<LitterFilter>;
  upcomingLitter?: InputMaybe<UpcomingLitterFilter>;
  page?: InputMaybe<PageFilter>;
  settings?: InputMaybe<SettingsFilter>;
  reviews?: InputMaybe<ReviewsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Litter | UpcomingLitter | Page | Settings | Reviews | Folder;

export type LitterPuppiesPhotos = {
  __typename?: 'LitterPuppiesPhotos';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type LitterPuppies = {
  __typename?: 'LitterPuppies';
  name?: Maybe<Scalars['String']['output']>;
  gender?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  photos?: Maybe<Array<Maybe<LitterPuppiesPhotos>>>;
};

export type LitterPreviousPuppies = {
  __typename?: 'LitterPreviousPuppies';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Litter = Node & Document & {
  __typename?: 'Litter';
  active?: Maybe<Scalars['Boolean']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  breeder?: Maybe<Scalars['String']['output']>;
  generation?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  litterTitle?: Maybe<Scalars['String']['output']>;
  dateOfBirth?: Maybe<Scalars['String']['output']>;
  takeHomeDate?: Maybe<Scalars['String']['output']>;
  estimatedSize?: Maybe<Scalars['String']['output']>;
  grooming?: Maybe<Scalars['String']['output']>;
  temperament?: Maybe<Scalars['String']['output']>;
  deposit?: Maybe<Scalars['String']['output']>;
  contact?: Maybe<Scalars['String']['output']>;
  damName?: Maybe<Scalars['String']['output']>;
  damDesc?: Maybe<Scalars['String']['output']>;
  damPhoto?: Maybe<Scalars['String']['output']>;
  sireName?: Maybe<Scalars['String']['output']>;
  sireDesc?: Maybe<Scalars['String']['output']>;
  cardDesc?: Maybe<Scalars['String']['output']>;
  cardPhoto?: Maybe<Scalars['String']['output']>;
  sirePhoto?: Maybe<Scalars['String']['output']>;
  puppies?: Maybe<Array<Maybe<LitterPuppies>>>;
  showCarousel?: Maybe<Scalars['Boolean']['output']>;
  showPrevCarousel?: Maybe<Scalars['Boolean']['output']>;
  previousPuppies?: Maybe<Array<Maybe<LitterPreviousPuppies>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type LitterPuppiesPhotosFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type LitterPuppiesFilter = {
  name?: InputMaybe<StringFilter>;
  gender?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  photos?: InputMaybe<LitterPuppiesPhotosFilter>;
};

export type LitterPreviousPuppiesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type LitterFilter = {
  active?: InputMaybe<BooleanFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  breeder?: InputMaybe<StringFilter>;
  generation?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  litterTitle?: InputMaybe<StringFilter>;
  dateOfBirth?: InputMaybe<StringFilter>;
  takeHomeDate?: InputMaybe<StringFilter>;
  estimatedSize?: InputMaybe<StringFilter>;
  grooming?: InputMaybe<StringFilter>;
  temperament?: InputMaybe<StringFilter>;
  deposit?: InputMaybe<StringFilter>;
  contact?: InputMaybe<StringFilter>;
  damName?: InputMaybe<StringFilter>;
  damDesc?: InputMaybe<StringFilter>;
  damPhoto?: InputMaybe<ImageFilter>;
  sireName?: InputMaybe<StringFilter>;
  sireDesc?: InputMaybe<StringFilter>;
  cardDesc?: InputMaybe<StringFilter>;
  cardPhoto?: InputMaybe<ImageFilter>;
  sirePhoto?: InputMaybe<ImageFilter>;
  puppies?: InputMaybe<LitterPuppiesFilter>;
  showCarousel?: InputMaybe<BooleanFilter>;
  showPrevCarousel?: InputMaybe<BooleanFilter>;
  previousPuppies?: InputMaybe<LitterPreviousPuppiesFilter>;
};

export type LitterConnectionEdges = {
  __typename?: 'LitterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Litter>;
};

export type LitterConnection = Connection & {
  __typename?: 'LitterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LitterConnectionEdges>>>;
};

export type UpcomingLitterPreviousPuppies = {
  __typename?: 'UpcomingLitterPreviousPuppies';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type UpcomingLitter = Node & Document & {
  __typename?: 'UpcomingLitter';
  active?: Maybe<Scalars['Boolean']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  breed: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  breeder?: Maybe<Scalars['String']['output']>;
  expectedDate?: Maybe<Scalars['String']['output']>;
  estimatedSize?: Maybe<Scalars['String']['output']>;
  cardDesc?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  cardPhoto?: Maybe<Scalars['String']['output']>;
  damName?: Maybe<Scalars['String']['output']>;
  damDesc?: Maybe<Scalars['String']['output']>;
  damPhoto?: Maybe<Scalars['String']['output']>;
  sireName?: Maybe<Scalars['String']['output']>;
  sireDesc?: Maybe<Scalars['String']['output']>;
  sirePhoto?: Maybe<Scalars['String']['output']>;
  previousPuppies?: Maybe<Array<Maybe<UpcomingLitterPreviousPuppies>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type UpcomingLitterPreviousPuppiesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type UpcomingLitterFilter = {
  active?: InputMaybe<BooleanFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
  breed?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  breeder?: InputMaybe<StringFilter>;
  expectedDate?: InputMaybe<StringFilter>;
  estimatedSize?: InputMaybe<StringFilter>;
  cardDesc?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cardPhoto?: InputMaybe<ImageFilter>;
  damName?: InputMaybe<StringFilter>;
  damDesc?: InputMaybe<StringFilter>;
  damPhoto?: InputMaybe<ImageFilter>;
  sireName?: InputMaybe<StringFilter>;
  sireDesc?: InputMaybe<StringFilter>;
  sirePhoto?: InputMaybe<ImageFilter>;
  previousPuppies?: InputMaybe<UpcomingLitterPreviousPuppiesFilter>;
};

export type UpcomingLitterConnectionEdges = {
  __typename?: 'UpcomingLitterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<UpcomingLitter>;
};

export type UpcomingLitterConnection = Connection & {
  __typename?: 'UpcomingLitterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UpcomingLitterConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  announcementBar?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  instagramUrl?: Maybe<Scalars['String']['output']>;
  cashappUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsFilter = {
  announcementBar?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  instagramUrl?: InputMaybe<StringFilter>;
  cashappUrl?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type ReviewsReviewImages = {
  __typename?: 'ReviewsReviewImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Reviews = Node & Document & {
  __typename?: 'Reviews';
  reviewImages?: Maybe<Array<Maybe<ReviewsReviewImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ReviewsReviewImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type ReviewsFilter = {
  reviewImages?: InputMaybe<ReviewsReviewImagesFilter>;
};

export type ReviewsConnectionEdges = {
  __typename?: 'ReviewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Reviews>;
};

export type ReviewsConnection = Connection & {
  __typename?: 'ReviewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReviewsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateLitter: Litter;
  createLitter: Litter;
  updateUpcomingLitter: UpcomingLitter;
  createUpcomingLitter: UpcomingLitter;
  updatePage: Page;
  createPage: Page;
  updateSettings: Settings;
  createSettings: Settings;
  updateReviews: Reviews;
  createReviews: Reviews;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateLitterArgs = {
  relativePath: Scalars['String']['input'];
  params: LitterMutation;
};


export type MutationCreateLitterArgs = {
  relativePath: Scalars['String']['input'];
  params: LitterMutation;
};


export type MutationUpdateUpcomingLitterArgs = {
  relativePath: Scalars['String']['input'];
  params: UpcomingLitterMutation;
};


export type MutationCreateUpcomingLitterArgs = {
  relativePath: Scalars['String']['input'];
  params: UpcomingLitterMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationCreateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};

export type DocumentUpdateMutation = {
  litter?: InputMaybe<LitterMutation>;
  upcomingLitter?: InputMaybe<UpcomingLitterMutation>;
  page?: InputMaybe<PageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  reviews?: InputMaybe<ReviewsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  litter?: InputMaybe<LitterMutation>;
  upcomingLitter?: InputMaybe<UpcomingLitterMutation>;
  page?: InputMaybe<PageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  reviews?: InputMaybe<ReviewsMutation>;
};

export type LitterPuppiesPhotosMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type LitterPuppiesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  gender?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  photos?: InputMaybe<Array<InputMaybe<LitterPuppiesPhotosMutation>>>;
};

export type LitterPreviousPuppiesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type LitterMutation = {
  active?: InputMaybe<Scalars['Boolean']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  breeder?: InputMaybe<Scalars['String']['input']>;
  generation?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  litterTitle?: InputMaybe<Scalars['String']['input']>;
  dateOfBirth?: InputMaybe<Scalars['String']['input']>;
  takeHomeDate?: InputMaybe<Scalars['String']['input']>;
  estimatedSize?: InputMaybe<Scalars['String']['input']>;
  grooming?: InputMaybe<Scalars['String']['input']>;
  temperament?: InputMaybe<Scalars['String']['input']>;
  deposit?: InputMaybe<Scalars['String']['input']>;
  contact?: InputMaybe<Scalars['String']['input']>;
  damName?: InputMaybe<Scalars['String']['input']>;
  damDesc?: InputMaybe<Scalars['String']['input']>;
  damPhoto?: InputMaybe<Scalars['String']['input']>;
  sireName?: InputMaybe<Scalars['String']['input']>;
  sireDesc?: InputMaybe<Scalars['String']['input']>;
  cardDesc?: InputMaybe<Scalars['String']['input']>;
  cardPhoto?: InputMaybe<Scalars['String']['input']>;
  sirePhoto?: InputMaybe<Scalars['String']['input']>;
  puppies?: InputMaybe<Array<InputMaybe<LitterPuppiesMutation>>>;
  showCarousel?: InputMaybe<Scalars['Boolean']['input']>;
  showPrevCarousel?: InputMaybe<Scalars['Boolean']['input']>;
  previousPuppies?: InputMaybe<Array<InputMaybe<LitterPreviousPuppiesMutation>>>;
};

export type UpcomingLitterPreviousPuppiesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type UpcomingLitterMutation = {
  active?: InputMaybe<Scalars['Boolean']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
  breed?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  breeder?: InputMaybe<Scalars['String']['input']>;
  expectedDate?: InputMaybe<Scalars['String']['input']>;
  estimatedSize?: InputMaybe<Scalars['String']['input']>;
  cardDesc?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cardPhoto?: InputMaybe<Scalars['String']['input']>;
  damName?: InputMaybe<Scalars['String']['input']>;
  damDesc?: InputMaybe<Scalars['String']['input']>;
  damPhoto?: InputMaybe<Scalars['String']['input']>;
  sireName?: InputMaybe<Scalars['String']['input']>;
  sireDesc?: InputMaybe<Scalars['String']['input']>;
  sirePhoto?: InputMaybe<Scalars['String']['input']>;
  previousPuppies?: InputMaybe<Array<InputMaybe<UpcomingLitterPreviousPuppiesMutation>>>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  announcementBar?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  instagramUrl?: InputMaybe<Scalars['String']['input']>;
  cashappUrl?: InputMaybe<Scalars['String']['input']>;
};

export type ReviewsReviewImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type ReviewsMutation = {
  reviewImages?: InputMaybe<Array<InputMaybe<ReviewsReviewImagesMutation>>>;
};

export type LitterPartsFragment = { __typename: 'Litter', active?: boolean | null, sortOrder?: number | null, title: string, slug?: string | null, breeder?: string | null, generation?: string | null, priceRange?: string | null, litterTitle?: string | null, dateOfBirth?: string | null, takeHomeDate?: string | null, estimatedSize?: string | null, grooming?: string | null, temperament?: string | null, deposit?: string | null, contact?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, cardDesc?: string | null, cardPhoto?: string | null, sirePhoto?: string | null, showCarousel?: boolean | null, showPrevCarousel?: boolean | null, puppies?: Array<{ __typename: 'LitterPuppies', name?: string | null, gender?: string | null, price?: string | null, status?: string | null, photos?: Array<{ __typename: 'LitterPuppiesPhotos', src?: string | null, alt?: string | null } | null> | null } | null> | null, previousPuppies?: Array<{ __typename: 'LitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null };

export type UpcomingLitterPartsFragment = { __typename: 'UpcomingLitter', active?: boolean | null, sortOrder?: number | null, breed: string, slug?: string | null, breeder?: string | null, expectedDate?: string | null, estimatedSize?: string | null, cardDesc?: string | null, description?: string | null, cardPhoto?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, sirePhoto?: string | null, previousPuppies?: Array<{ __typename: 'UpcomingLitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null };

export type PagePartsFragment = { __typename: 'Page', title?: string | null, heroHeading?: string | null, heroSubtext?: string | null };

export type SettingsPartsFragment = { __typename: 'Settings', announcementBar?: string | null, phone?: string | null, email?: string | null, instagramUrl?: string | null, cashappUrl?: string | null };

export type ReviewsPartsFragment = { __typename: 'Reviews', reviewImages?: Array<{ __typename: 'ReviewsReviewImages', src?: string | null, alt?: string | null } | null> | null };

export type LitterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LitterQuery = { __typename?: 'Query', litter: { __typename: 'Litter', id: string, active?: boolean | null, sortOrder?: number | null, title: string, slug?: string | null, breeder?: string | null, generation?: string | null, priceRange?: string | null, litterTitle?: string | null, dateOfBirth?: string | null, takeHomeDate?: string | null, estimatedSize?: string | null, grooming?: string | null, temperament?: string | null, deposit?: string | null, contact?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, cardDesc?: string | null, cardPhoto?: string | null, sirePhoto?: string | null, showCarousel?: boolean | null, showPrevCarousel?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, puppies?: Array<{ __typename: 'LitterPuppies', name?: string | null, gender?: string | null, price?: string | null, status?: string | null, photos?: Array<{ __typename: 'LitterPuppiesPhotos', src?: string | null, alt?: string | null } | null> | null } | null> | null, previousPuppies?: Array<{ __typename: 'LitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null } };

export type LitterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LitterFilter>;
}>;


export type LitterConnectionQuery = { __typename?: 'Query', litterConnection: { __typename?: 'LitterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LitterConnectionEdges', cursor: string, node?: { __typename: 'Litter', id: string, active?: boolean | null, sortOrder?: number | null, title: string, slug?: string | null, breeder?: string | null, generation?: string | null, priceRange?: string | null, litterTitle?: string | null, dateOfBirth?: string | null, takeHomeDate?: string | null, estimatedSize?: string | null, grooming?: string | null, temperament?: string | null, deposit?: string | null, contact?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, cardDesc?: string | null, cardPhoto?: string | null, sirePhoto?: string | null, showCarousel?: boolean | null, showPrevCarousel?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, puppies?: Array<{ __typename: 'LitterPuppies', name?: string | null, gender?: string | null, price?: string | null, status?: string | null, photos?: Array<{ __typename: 'LitterPuppiesPhotos', src?: string | null, alt?: string | null } | null> | null } | null> | null, previousPuppies?: Array<{ __typename: 'LitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export type UpcomingLitterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type UpcomingLitterQuery = { __typename?: 'Query', upcomingLitter: { __typename: 'UpcomingLitter', id: string, active?: boolean | null, sortOrder?: number | null, breed: string, slug?: string | null, breeder?: string | null, expectedDate?: string | null, estimatedSize?: string | null, cardDesc?: string | null, description?: string | null, cardPhoto?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, sirePhoto?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, previousPuppies?: Array<{ __typename: 'UpcomingLitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null } };

export type UpcomingLitterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UpcomingLitterFilter>;
}>;


export type UpcomingLitterConnectionQuery = { __typename?: 'Query', upcomingLitterConnection: { __typename?: 'UpcomingLitterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'UpcomingLitterConnectionEdges', cursor: string, node?: { __typename: 'UpcomingLitter', id: string, active?: boolean | null, sortOrder?: number | null, breed: string, slug?: string | null, breeder?: string | null, expectedDate?: string | null, estimatedSize?: string | null, cardDesc?: string | null, description?: string | null, cardPhoto?: string | null, damName?: string | null, damDesc?: string | null, damPhoto?: string | null, sireName?: string | null, sireDesc?: string | null, sirePhoto?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, previousPuppies?: Array<{ __typename: 'UpcomingLitterPreviousPuppies', src?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title?: string | null, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title?: string | null, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, announcementBar?: string | null, phone?: string | null, email?: string | null, instagramUrl?: string | null, cashappUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, announcementBar?: string | null, phone?: string | null, email?: string | null, instagramUrl?: string | null, cashappUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ReviewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReviewsQuery = { __typename?: 'Query', reviews: { __typename: 'Reviews', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, reviewImages?: Array<{ __typename: 'ReviewsReviewImages', src?: string | null, alt?: string | null } | null> | null } };

export type ReviewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
}>;


export type ReviewsConnectionQuery = { __typename?: 'Query', reviewsConnection: { __typename?: 'ReviewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReviewsConnectionEdges', cursor: string, node?: { __typename: 'Reviews', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, reviewImages?: Array<{ __typename: 'ReviewsReviewImages', src?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export const LitterPartsFragmentDoc = gql`
    fragment LitterParts on Litter {
  __typename
  active
  sortOrder
  title
  slug
  breeder
  generation
  priceRange
  litterTitle
  dateOfBirth
  takeHomeDate
  estimatedSize
  grooming
  temperament
  deposit
  contact
  damName
  damDesc
  damPhoto
  sireName
  sireDesc
  cardDesc
  cardPhoto
  sirePhoto
  puppies {
    __typename
    name
    gender
    price
    status
    photos {
      __typename
      src
      alt
    }
  }
  showCarousel
  showPrevCarousel
  previousPuppies {
    __typename
    src
    alt
  }
}
    `;
export const UpcomingLitterPartsFragmentDoc = gql`
    fragment UpcomingLitterParts on UpcomingLitter {
  __typename
  active
  sortOrder
  breed
  slug
  breeder
  expectedDate
  estimatedSize
  cardDesc
  description
  cardPhoto
  damName
  damDesc
  damPhoto
  sireName
  sireDesc
  sirePhoto
  previousPuppies {
    __typename
    src
    alt
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  heroHeading
  heroSubtext
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  announcementBar
  phone
  email
  instagramUrl
  cashappUrl
}
    `;
export const ReviewsPartsFragmentDoc = gql`
    fragment ReviewsParts on Reviews {
  __typename
  reviewImages {
    __typename
    src
    alt
  }
}
    `;
export const LitterDocument = gql`
    query litter($relativePath: String!) {
  litter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LitterParts
  }
}
    ${LitterPartsFragmentDoc}`;
export const LitterConnectionDocument = gql`
    query litterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LitterFilter) {
  litterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LitterParts
      }
    }
  }
}
    ${LitterPartsFragmentDoc}`;
export const UpcomingLitterDocument = gql`
    query upcomingLitter($relativePath: String!) {
  upcomingLitter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UpcomingLitterParts
  }
}
    ${UpcomingLitterPartsFragmentDoc}`;
export const UpcomingLitterConnectionDocument = gql`
    query upcomingLitterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UpcomingLitterFilter) {
  upcomingLitterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UpcomingLitterParts
      }
    }
  }
}
    ${UpcomingLitterPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const ReviewsDocument = gql`
    query reviews($relativePath: String!) {
  reviews(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReviewsParts
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const ReviewsConnectionDocument = gql`
    query reviewsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReviewsFilter) {
  reviewsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReviewsParts
      }
    }
  }
}
    ${ReviewsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      litter(variables: LitterQueryVariables, options?: C): Promise<{data: LitterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LitterQueryVariables, query: string}> {
        return requester<{data: LitterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LitterQueryVariables, query: string}, LitterQueryVariables>(LitterDocument, variables, options);
      },
    litterConnection(variables?: LitterConnectionQueryVariables, options?: C): Promise<{data: LitterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LitterConnectionQueryVariables, query: string}> {
        return requester<{data: LitterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LitterConnectionQueryVariables, query: string}, LitterConnectionQueryVariables>(LitterConnectionDocument, variables, options);
      },
    upcomingLitter(variables: UpcomingLitterQueryVariables, options?: C): Promise<{data: UpcomingLitterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpcomingLitterQueryVariables, query: string}> {
        return requester<{data: UpcomingLitterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpcomingLitterQueryVariables, query: string}, UpcomingLitterQueryVariables>(UpcomingLitterDocument, variables, options);
      },
    upcomingLitterConnection(variables?: UpcomingLitterConnectionQueryVariables, options?: C): Promise<{data: UpcomingLitterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpcomingLitterConnectionQueryVariables, query: string}> {
        return requester<{data: UpcomingLitterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpcomingLitterConnectionQueryVariables, query: string}, UpcomingLitterConnectionQueryVariables>(UpcomingLitterConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    reviews(variables: ReviewsQueryVariables, options?: C): Promise<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}> {
        return requester<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}, ReviewsQueryVariables>(ReviewsDocument, variables, options);
      },
    reviewsConnection(variables?: ReviewsConnectionQueryVariables, options?: C): Promise<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}> {
        return requester<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}, ReviewsConnectionQueryVariables>(ReviewsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  