[build]
  command = "tinacms build --skip-cloud-checks && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_TINA_CLIENT_ID,TINA_TOKEN"
